server:
  servlet:
    context-path: /catalogue
  port: 8002
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/catalogue
    username: postgres
    password: postgres
  data:
    web:
      pageable:
        one-indexed-parameters: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-service:9000
