auth-server:
  http://auth-service:8888
realm-name:
  dev
server:
  servlet:
    context-path: /catalogue
  port: 8002
spring:
  data:
    web:
      pageable:
        one-indexed-parameters: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${auth-server}/realms/${realm-name}
