server:
  servlet:
    context-path: /classifier
  port: 8001
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/classifier
    username: postgres
    password: postgres
  data:
    web:
      pageable:
        one-indexed-parameters: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-service:9000
currency-rates-api:
  api-key: 89T51IDzBjPz4lZkwe7mY1D72lfMd9j6
  base: USD
  url: https://api.apilayer.com/exchangerates_data/latest?base=${currency-rates-api.base}&symbols=
  exchange-rate:
    cron: 0 0 0 * * *
    timezone: UTC
