server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: classifier-service
          uri: lb://classifier-service
          predicates:
           - Path=/classifier/**
        - id: catalogue-service
          uri: lb://catalogue-service
          predicates:
          - Path=/catalogue/**
