auth-server:
  http://auth-service:8888
realm-name:
  dev
server:
  port: 8080
spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: classifier-service
          uri: lb://classifier-service
          predicates:
           - Path=/classifier/**
        - id: catalogue-service
          uri: lb://catalogue-service
          predicates:
           - Path=/catalogue/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${auth-server}/realms/${realm-name}
        registration:
          online-store:
            provider: keycloak
            client-id: online-store
            authorization-grant-type: authorization_code
            client-secret: qC0YE9ur2OQw2jDz1AQZCeLuw8ECBWvl
            scope: openid
      resourceserver:
        jwt:
          issuer-uri: ${auth-server}/realms/${realm-name}
logging:
  level:
    org:
      springframework:
        security: DEBUG