server:
  port: 8080
spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: classifier-service
          uri: lb://classifier-service
          predicates:
           - Path=/classifier/**
        - id: catalogue-service
          uri: lb://catalogue-service
          predicates:
           - Path=/catalogue/**
        - id: auth-service
          uri: http://auth-service:9000
          predicates:
            - Path=/auth/**
  security:
    oauth2:
      client:
        registration:
          gateway-client:
            provider: auth-service
            client-id: gateway-client-id
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://spring-gateway:8080/login/oauth2/code/{registrationId}"
            scope: openid, store.read, store.write
            client-name: gateway-client
        provider:
          auth-service:
            issuer-uri: http://auth-service:9000