auth-server:
  http://auth-service:8888
server:
  servlet:
    context-path: /order
  port: 8003
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
logging:
  level:
    org:
      springframework:
        security: DEBUG
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/order
    username: postgres
    password: postgres
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${auth-server}/realms/dev
keycloak:
  service-authentication:
    username: order-service
    password: 123
    client-id: online-store
    client-secret: qC0YE9ur2OQw2jDz1AQZCeLuw8ECBWvl
    token-url: ${auth-server}/realms/dev/protocol/openid-connect/token